[tool.poetry]
name = "onlinestore1"
version = "0.1.0"
description = ""
authors = ["«Artyom» <«lzspector@mail.ru»>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.14"
flake8 = "^7.3.0"
mypy = "^2.1.0"
pytest = "^9.0.3"
isort = "^8.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
